Remove prettier plugin from pre-commit config
Running `poetry run pre-commit run --all-files` resulted in the following error:
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

Not loosing much if html|md|yml|yaml are no longer formatted. Maybe someone
finds a fix / better solution for this.